all:
	gcc hw6_client.c -o hw6_client  -pthread
	gcc hw6_server.c -o hw6_server
	gcc server.c -o server
	gcc client.c -o client -pthread
	gcc thread.c -o thread -pthread
	gcc thread_test.c -o thread_test -pthread
	gcc pipe.c -o pipe
	gcc test.c -o test
